/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring.index'
import { Route as MonitoringPatientIdRouteImport } from './routes/monitoring.$patientId'
import { Route as RecordsIndexRouteImport } from './routes/records.index'
import { Route as RecordsPatientIdRouteImport } from './routes/records.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringPatientIdRoute = MonitoringPatientIdRouteImport.update({
  id: '/monitoring/$patientId',
  path: '/monitoring/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsPatientIdRoute = RecordsPatientIdRouteImport.update({
  id: '/records/$patientId',
  path: '/records/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/monitoring/$patientId': typeof MonitoringPatientIdRoute
  '/records/$patientId': typeof RecordsPatientIdRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/monitoring/$patientId': typeof MonitoringPatientIdRoute
  '/records/$patientId': typeof RecordsPatientIdRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/records': typeof RecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/monitoring/$patientId': typeof MonitoringPatientIdRoute
  '/records/$patientId': typeof RecordsPatientIdRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/records/': typeof RecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/monitoring/$patientId'
    | '/records/$patientId'
    | '/monitoring/'
    | '/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/monitoring/$patientId'
    | '/records/$patientId'
    | '/monitoring'
    | '/records'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/monitoring/$patientId'
    | '/records/$patientId'
    | '/monitoring/'
    | '/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  MonitoringPatientIdRoute: typeof MonitoringPatientIdRoute
  RecordsPatientIdRoute: typeof RecordsPatientIdRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/$patientId': {
      id: '/monitoring/$patientId'
      path: '/monitoring/$patientId'
      fullPath: '/monitoring/$patientId'
      preLoaderRoute: typeof MonitoringPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$patientId': {
      id: '/records/$patientId'
      path: '/records/$patientId'
      fullPath: '/records/$patientId'
      preLoaderRoute: typeof RecordsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  MonitoringPatientIdRoute: MonitoringPatientIdRoute,
  RecordsPatientIdRoute: RecordsPatientIdRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  RecordsIndexRoute: RecordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
